### ISSUE TITLE
Investigate keyboard/mouse states

### ISSUE THREAD

**Issue by holdemani** [LoganTHarvell/Astral-Pathfinder#21]
Fix frames so mouse doesn't hoard them all

“SDL2 uses SDL_GetKeyboardState().  It's mostly the same as how SDL1.2 did it, though.  The biggest difference is that instead of using keycodes (e.g. SDLK_LEFT), you have to use scancodes (e.g. SDL_SCANCODE_LEFT or SDL_GetScancodeFromKey(SDLK_LEFT)) or else expect crashing.”
^ look into that

**Comment by LoganTHarvell** [comment]
This should be named "investigate SDL2 keyboard/mouse states" or something

**Comment by holdemani** [comment]
Ugh you're lame
