### ISSUE TITLE
Memory leak during planet selection

### ISSUE THREAD

**Issue by LoganTHarvell** [LoganTHarvell/Astral-Pathfinder#30]
Textures repeatedly allocated when planet selected. Need to rework the code.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by holdemani** [comment]
Spamming clean() functions fixes memory increasing, but not CPU usage

I like this guy's answer to save some CPU: https://stackoverflow.com/questions/21349656/sdl-textures-and-cpu-memory-issues

Won't work for all our textures but it's a start
