### ISSUE TITLE
UI fixes and changes

### ISSUE THREAD

**Issue by LoganTHarvell** [LoganTHarvell/Astral-Pathfinder#34]
Adding this here:

- [x] 1. Ship and Planet location should both begin using a standardized position, such as map position (where their location is relative to the map origin)
- [x] 2. Population/Crew should be moved to the left side of the UI screens, swapping the location and fuel text to the right side
- [x] 3. Reduce clean() calls to only where necessary, this will increase performance
- [x] 4. Update sizing for new font
- [x] 5. **Visually see dead colonies**
- [x] 6. **Visually see colonies that have been declining population for an extended period**
- [x] 7. Visually see max population aka infrastructure
- [x] 8. Give each planet a random center point offset within their "grid" to reduce planets in a line
- [x] 9. **Add Total Population to UI**

**Comment by LoganTHarvell** [comment]
**Bugs**:

The bar separating docked planet info seems to be hidden by other textboxes. 
Not a huge issue.
Might be better to just adjust the background image to have a bar.

**Comment by LoganTHarvell** [comment]
Task 6, visually showing declining populations for an extended period (probably checking for negative growth during an entire growth period), might be able to be done by adding text to the events screen referencing the planet that is declining. Maybe in addition to making the planet yellow?

**Comment by holdemani** [comment]
I don't see the point for task 4. The font looks fine.

**Comment by holdemani** [comment]
Task 3: ShipInfo clean calls have been reduced, and don't clean the values that don't change. I don't think there's any other unnecessary clean calls

**Comment by holdemani** [comment]
Task 1: Ship was already using getCenter() so I switched the planet coords to follow
