### ISSUE TITLE
Gameplay Tweaks

### ISSUE THREAD

**Issue by LoganTHarvell** [LoganTHarvell/Astral-Pathfinder#36]
Many things will need to be tweaked and changed over time. This will be a thread of requests and suggestions.

- [x] Mining is too slow, not enough fuel to get around, not enough infrastructure
- [x] Need to see when a population is declining for an entire growth period (requested in issue #34), then increase farming percent incrementally
- [x] Be able to see current infrastructure (requested in issue #34) 
- [x] Growth period is currently too long, should shorten
- [x] Increase starvation rate
- [x] Reduce number of planets, probably then increase planet texture size
- ~~Mining feels slow when at a planet with lots of minerals~~
- [x] Population growth rate might need to be made slower
- [x] Infrastructure goes down by 1000 when ship leaves, misleading how much a planet actually has

**Comment by holdemani** [comment]
Hmmmm I guess me finishing my issue marks yours done as well

**Comment by holdemani** [comment]
@LoganTHarvell there, I gave you something to do

**Comment by LoganTHarvell** [comment]
lol but that typo @iholdeman1

**Comment by holdemani** [comment]
Idk what you're talking about @LoganTHarvell. That's a flawless sentence

**Comment by holdemani** [comment]
@LoganTHarvell I feel as though the yellow indicator for a decreasing population should happen a little sooner. I feel I lose a decent amount of people before it's indicated.

**Comment by LoganTHarvell** [comment]
I’ll keep that in mind but tbh, population grows so fast at the moment that I don’t see that being an issue until the growth rate is changed @iholdeman1 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
